# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0effa2924d122e5fe293393bd4a3a737c1396674184f17e62634bc36d34d9a68f88667535f20dab84803a411d87d9dedcf8b02000ba1ed22760049b76e816d2d

test:
  secret_key_base: 2095aa65e41252945cc2ba9acb01d5c0120adb99a015349047b4104bc1caea6b5520f470166fd222377cdaa9ef22fea9a1eb9c3b03cb2d4dfb24e761783f8ad5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
